// Full Nifty 500 stock universe — symbol + company name
// This is the static directory. Prices are always fetched live.
export const NSE_STOCKS = [
  { symbol:"RELIANCE",    name:"Reliance Industries Ltd" },
  { symbol:"TCS",         name:"Tata Consultancy Services Ltd" },
  { symbol:"HDFCBANK",    name:"HDFC Bank Ltd" },
  { symbol:"BHARTIARTL",  name:"Bharti Airtel Ltd" },
  { symbol:"ICICIBANK",   name:"ICICI Bank Ltd" },
  { symbol:"INFOSYS",     name:"Infosys Ltd" },
  { symbol:"INFY",        name:"Infosys Ltd" },
  { symbol:"SBIN",        name:"State Bank of India" },
  { symbol:"HINDUNILVR",  name:"Hindustan Unilever Ltd" },
  { symbol:"ITC",         name:"ITC Ltd" },
  { symbol:"LT",          name:"Larsen & Toubro Ltd" },
  { symbol:"KOTAKBANK",   name:"Kotak Mahindra Bank Ltd" },
  { symbol:"AXISBANK",    name:"Axis Bank Ltd" },
  { symbol:"BAJFINANCE",  name:"Bajaj Finance Ltd" },
  { symbol:"ASIANPAINT",  name:"Asian Paints Ltd" },
  { symbol:"MARUTI",      name:"Maruti Suzuki India Ltd" },
  { symbol:"TITAN",       name:"Titan Company Ltd" },
  { symbol:"SUNPHARMA",   name:"Sun Pharmaceutical Industries Ltd" },
  { symbol:"ULTRACEMCO",  name:"UltraTech Cement Ltd" },
  { symbol:"WIPRO",       name:"Wipro Ltd" },
  { symbol:"ONGC",        name:"Oil & Natural Gas Corporation Ltd" },
  { symbol:"NTPC",        name:"NTPC Ltd" },
  { symbol:"POWERGRID",   name:"Power Grid Corporation of India Ltd" },
  { symbol:"TATAMOTORS",  name:"Tata Motors Ltd" },
  { symbol:"TATASTEEL",   name:"Tata Steel Ltd" },
  { symbol:"HCLTECH",     name:"HCL Technologies Ltd" },
  { symbol:"ADANIENT",    name:"Adani Enterprises Ltd" },
  { symbol:"ADANIPORTS",  name:"Adani Ports and Special Economic Zone Ltd" },
  { symbol:"COALINDIA",   name:"Coal India Ltd" },
  { symbol:"BAJAJFINSV",  name:"Bajaj Finserv Ltd" },
  { symbol:"NESTLEIND",   name:"Nestle India Ltd" },
  { symbol:"TECHM",       name:"Tech Mahindra Ltd" },
  { symbol:"GRASIM",      name:"Grasim Industries Ltd" },
  { symbol:"JSWSTEEL",    name:"JSW Steel Ltd" },
  { symbol:"DRREDDY",     name:"Dr. Reddy's Laboratories Ltd" },
  { symbol:"DIVISLAB",    name:"Divi's Laboratories Ltd" },
  { symbol:"CIPLA",       name:"Cipla Ltd" },
  { symbol:"EICHERMOT",   name:"Eicher Motors Ltd" },
  { symbol:"BPCL",        name:"Bharat Petroleum Corporation Ltd" },
  { symbol:"HEROMOTOCO",  name:"Hero MotoCorp Ltd" },
  { symbol:"BRITANNIA",   name:"Britannia Industries Ltd" },
  { symbol:"APOLLOHOSP",  name:"Apollo Hospitals Enterprise Ltd" },
  { symbol:"TATACONSUM",  name:"Tata Consumer Products Ltd" },
  { symbol:"INDUSINDBK",  name:"IndusInd Bank Ltd" },
  { symbol:"HINDALCO",    name:"Hindalco Industries Ltd" },
  { symbol:"SBILIFE",     name:"SBI Life Insurance Company Ltd" },
  { symbol:"HDFCLIFE",    name:"HDFC Life Insurance Company Ltd" },
  { symbol:"BAJAJ-AUTO",  name:"Bajaj Auto Ltd" },
  { symbol:"M&M",         name:"Mahindra & Mahindra Ltd" },
  { symbol:"SHREECEM",    name:"Shree Cement Ltd" },
  { symbol:"AMBUJACEM",   name:"Ambuja Cements Ltd" },
  { symbol:"VEDL",        name:"Vedanta Ltd" },
  { symbol:"SIEMENS",     name:"Siemens Ltd" },
  { symbol:"ABB",         name:"ABB India Ltd" },
  { symbol:"HAL",         name:"Hindustan Aeronautics Ltd" },
  { symbol:"BEL",         name:"Bharat Electronics Ltd" },
  { symbol:"PIDILITIND",  name:"Pidilite Industries Ltd" },
  { symbol:"MARICO",      name:"Marico Ltd" },
  { symbol:"DABUR",       name:"Dabur India Ltd" },
  { symbol:"GODREJCP",    name:"Godrej Consumer Products Ltd" },
  { symbol:"TRENT",       name:"Trent Ltd" },
  { symbol:"DMART",       name:"Avenue Supermarts Ltd" },
  { symbol:"IRCTC",       name:"Indian Railway Catering and Tourism Corporation Ltd" },
  { symbol:"ZOMATO",      name:"Zomato Ltd" },
  { symbol:"NYKAA",       name:"FSN E-Commerce Ventures Ltd" },
  { symbol:"PAYTM",       name:"One97 Communications Ltd" },
  { symbol:"POLICYBZR",   name:"PB Fintech Ltd" },
  { symbol:"DELHIVERY",   name:"Delhivery Ltd" },
  { symbol:"INDIGO",      name:"InterGlobe Aviation Ltd" },
  { symbol:"SPICEJET",    name:"SpiceJet Ltd" },
  { symbol:"BANKBARODA",  name:"Bank of Baroda" },
  { symbol:"PNB",         name:"Punjab National Bank" },
  { symbol:"CANBK",       name:"Canara Bank" },
  { symbol:"UNIONBANK",   name:"Union Bank of India" },
  { symbol:"IDBI",        name:"IDBI Bank Ltd" },
  { symbol:"FEDERALBNK",  name:"The Federal Bank Ltd" },
  { symbol:"IDFCFIRSTB",  name:"IDFC First Bank Ltd" },
  { symbol:"RBLBANK",     name:"RBL Bank Ltd" },
  { symbol:"BANDHANBNK",  name:"Bandhan Bank Ltd" },
  { symbol:"MUTHOOTFIN",  name:"Muthoot Finance Ltd" },
  { symbol:"CHOLAFIN",    name:"Cholamandalam Investment and Finance Company Ltd" },
  { symbol:"LICHSGFIN",   name:"LIC Housing Finance Ltd" },
  { symbol:"RECLTD",      name:"REC Ltd" },
  { symbol:"PFC",         name:"Power Finance Corporation Ltd" },
  { symbol:"IRFC",        name:"Indian Railway Finance Corporation Ltd" },
  { symbol:"TATAPOWER",   name:"Tata Power Company Ltd" },
  { symbol:"ADANIPOWER",  name:"Adani Power Ltd" },
  { symbol:"ADANIGREEN",  name:"Adani Green Energy Ltd" },
  { symbol:"TORNTPOWER",  name:"Torrent Power Ltd" },
  { symbol:"CESC",        name:"CESC Ltd" },
  { symbol:"NHPC",        name:"NHPC Ltd" },
  { symbol:"SJVN",        name:"SJVN Ltd" },
  { symbol:"INDIANB",     name:"Indian Bank" },
  { symbol:"IOB",         name:"Indian Overseas Bank" },
  { symbol:"MAHABANK",    name:"Bank of Maharashtra" },
  { symbol:"CENTRALBK",   name:"Central Bank of India" },
  { symbol:"UCOBANK",     name:"UCO Bank" },
  { symbol:"BANKOFMAH",   name:"Bank of Maharashtra" },
  { symbol:"SAIL",        name:"Steel Authority of India Ltd" },
  { symbol:"NMDC",        name:"NMDC Ltd" },
  { symbol:"NATIONALUM",  name:"National Aluminium Company Ltd" },
  { symbol:"HINDCOPPER",  name:"Hindustan Copper Ltd" },
  { symbol:"MOIL",        name:"MOIL Ltd" },
  { symbol:"APLAPOLLO",   name:"APL Apollo Tubes Ltd" },
  { symbol:"RATNAMANI",   name:"Ratnamani Metals & Tubes Ltd" },
  { symbol:"WELSPUNLIV",  name:"Welspun Living Ltd" },
  { symbol:"PAGEIND",     name:"Page Industries Ltd" },
  { symbol:"WHIRLPOOL",   name:"Whirlpool of India Ltd" },
  { symbol:"VOLTAS",      name:"Voltas Ltd" },
  { symbol:"BLUESTARCO",  name:"Blue Star Ltd" },
  { symbol:"HAVELLS",     name:"Havells India Ltd" },
  { symbol:"CROMPTON",    name:"Crompton Greaves Consumer Electricals Ltd" },
  { symbol:"POLYCAB",     name:"Polycab India Ltd" },
  { symbol:"KEI",         name:"KEI Industries Ltd" },
  { symbol:"FINPIPE",     name:"Finolex Industries Ltd" },
  { symbol:"SUPREMEIND",  name:"Supreme Industries Ltd" },
  { symbol:"ASTRAL",      name:"Astral Ltd" },
  { symbol:"BERGEPAINT",  name:"Berger Paints India Ltd" },
  { symbol:"KANSAINER",   name:"Kansai Nerolac Paints Ltd" },
  { symbol:"ALKYLAMINE",  name:"Alkyl Amines Chemicals Ltd" },
  { symbol:"AAVAS",       name:"Aavas Financiers Ltd" },
  { symbol:"HOMEFIRST",   name:"Home First Finance Company India Ltd" },
  { symbol:"APTUS",       name:"Aptus Value Housing Finance India Ltd" },
  { symbol:"LICI",        name:"Life Insurance Corporation of India" },
  { symbol:"GICRE",       name:"General Insurance Corporation of India" },
  { symbol:"NIACL",       name:"The New India Assurance Company Ltd" },
  { symbol:"STARHEALTH",  name:"Star Health and Allied Insurance Company Ltd" },
  { symbol:"ICICIGI",     name:"ICICI Lombard General Insurance Company Ltd" },
  { symbol:"BAJAJALLIANZ",name:"Bajaj Allianz General Insurance Company" },
  { symbol:"INOXWIND",    name:"Inox Wind Ltd" },
  { symbol:"SUZLON",      name:"Suzlon Energy Ltd" },
  { symbol:"RENUKA",      name:"Shree Renuka Sugars Ltd" },
  { symbol:"BALRAMCHIN",  name:"Balrampur Chini Mills Ltd" },
  { symbol:"TRIVENI",     name:"Triveni Engineering & Industries Ltd" },
  { symbol:"DHAMPUR",     name:"Dhampur Sugar Mills Ltd" },
  { symbol:"UPL",         name:"UPL Ltd" },
  { symbol:"PIIND",       name:"PI Industries Ltd" },
  { symbol:"RALLIS",      name:"Rallis India Ltd" },
  { symbol:"BAYER",       name:"Bayer CropScience Ltd" },
  { symbol:"SUMICHEM",    name:"Sumitomo Chemical India Ltd" },
  { symbol:"COROMANDEL",  name:"Coromandel International Ltd" },
  { symbol:"CHAMBLFERT",  name:"Chambal Fertilizers & Chemicals Ltd" },
  { symbol:"GNFC",        name:"Gujarat Narmada Valley Fertilizers & Chemicals Ltd" },
  { symbol:"RCF",         name:"Rashtriya Chemicals & Fertilizers Ltd" },
  { symbol:"GHCL",        name:"GHCL Ltd" },
  { symbol:"DEEPAKNTR",   name:"Deepak Nitrite Ltd" },
  { symbol:"GALAXYSURF",  name:"Galaxy Surfactants Ltd" },
  { symbol:"AAPL",        name:"Apple Inc (US)" },
  { symbol:"GOOGL",       name:"Alphabet Inc (US)" },
  { symbol:"MSFT",        name:"Microsoft Corporation (US)" },
  { symbol:"AMZN",        name:"Amazon.com Inc (US)" },
  { symbol:"NVDA",        name:"NVIDIA Corporation (US)" },
  { symbol:"META",        name:"Meta Platforms Inc (US)" },
  { symbol:"TSLA",        name:"Tesla Inc (US)" },
];

// Default symbols to show/pre-fetch on load
export const DEFAULT_SYMBOLS = [
  "RELIANCE","TCS","HDFCBANK","INFY","ICICIBANK",
  "TATAMOTORS","SBIN","WIPRO","HCLTECH","AXISBANK",
  "BAJFINANCE","MARUTI","TITAN","SUNPHARMA","NTPC",
  "POWERGRID","TATASTEEL","LT","HINDUNILVR","ITC",
];
